spring.application.name: AWSDeployable
server.port: 8082
server.address: 0.0.0.0
management.endpoints.web.exposure.include: health
management.endpoint.health.show-details: always
spring.data.mongodb.uri: mongodb+srv://rupeshmathur:mathur1992@atlascluster.geucstt.mongodb.net/notification_db?retryWrites=true&w=majority&tls=true
spring.task.scheduling.time-zone: Asia/Kolkata
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: mathurupesh92@gmail.com
spring.mail.password: pmyr jebb tnpz vpwu
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
